### PR TITLE
Add new trove classifiers

### PR DESCRIPTION
**Pull request by krassowski**
See https://github.com/jupyterlab/jupyterlab/pull/10731

### CODE REVIEW

**Comment by ocordes** [comment]
Sorry, I've read this today, because I was busy with the flood catastrophe in Germany. This PR sound good to me, I will change my own extensions as well ;-)

**Comment by krassowski** [comment]
I will mark this one as a draft because while the new classfiers were accepted and merged into the https://github.com/pypa/trove-classifiers/pull/72 we are still waiting for a new PyPI Warehouse release with the updated version of trove-cassifiers: https://github.com/pypa/warehouse/pull/9882

**Comment by krassowski** [comment]
This is now available https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Jupyter+%3A%3A+JupyterLab+%3A%3A+Extensions :tada: @ocordes it is a good time to add those to your extensions as we will be switching to searching extensions using these classifiers. I hope you all recovered from the flood!

**Comment by ocordes** [comment]
Okay, thnx for the info. I updated my extensions as well :-) We are rebuilding our house at the moment, hopefully we have a functional heating until the winter month.

**Pull request merged**
